.Dd Aug 22, 2011
.Dt fdupves 1
.Os
.Sh NAME
.Nm fdupves
.Nd find duplicate vidoe/image files
.Sh SYNOPSIS
.Nm
.Op options
.Sh DESCRIPTION
fdupves is a blog pulisher, which can publish article to multiple blogs once.
.Sh OPTIONS
.Bl -tag -width "v"
.It Fl h
Show help message and exit
.It Fl v
Show version and exit
.El
.Sh SETTINGS
.El
.Sh AUTHORS
fdupves was written by Alf <naihe2010@126.com>.
.Pp
This manual page was written by Alf <naihe2010@126.com>
